server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/schema
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

  devtools: #热部署
    restart:
      enabled: true
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**

  application:
      name: microservice-provider-user  # 用于指定注册到Eureka Server上的应用名称

eureka:
  client:
    serviceUrl:
      defaultZooe: http://localhost:8761/eureka/
  instance:
    perfer-ip-address: true #将自己IP注册到Eureka Server

