server:
  port: 8761

eureka:
  client:
    # 是否将自己注册到Eureka Server，默认是true。由于当前应用就是Eureka Server，故设false
    registerWithEureka: false
    #表示是否从Eureka Server获取注册信息，默认是true。由于这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故设false
    fetchRegistry: false
    serviceUrl:
      #设置与Eureka Server交互的地址。多个地址可使用，分隔。这里将自己注册到peer2这个Eureka上面去
      defaultZone: http://localhost:8761/eureka/



