spring:
  application:
    name: microservice-discovery-eureka

#用户认证
security:
  basic:
    enabled: true  #开启基于Http basic的认证
  user:
    name: admin #配置对了的账户是admin
    password: admin #配置登录密码是admin

---

spring:
  #指定profile=peer1
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    # 指定当profile=peer1时，主机名是peer1
    hostname: peer1
  client:
    # 是否将自己注册到Eureka Server，默认是true。由于当前应用就是Eureka Server，故设false
    registerWithEureka: false
    #表示是否从Eureka Server获取注册信息，默认是true。由于这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故设false
    fetchRegistry: false
    serviceUrl:
      #设置与Eureka Server交互的地址。多个地址可使用，分隔。这里将自己注册到peer2这个Eureka上面去
      defaultZone: http://admin:admin@peer2:8762/eureka/
---

spring:
  #指定profile=peer2
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    # 指定当profile=peer2时，主机名是peer2
    hostname: peer2
  client:
    # 是否将自己注册到Eureka Server，默认是true。由于当前应用就是Eureka Server，故设false
    registerWithEureka: false
    #表示是否从Eureka Server获取注册信息，默认是true。由于这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故设false
    fetchRegistry: false
    serviceUrl:
      #设置与Eureka Server交互的地址。多个地址可使用，分隔。这里将自己注册到peer1这个Eureka上面去
      defaultZone: http://admin:admin@peer1:8761/eureka/



